name: Run Book Scraper Daily

on:
  schedule:
    - cron: "0 15 * * *"  # runs every day at 12:00 UTC
  workflow_dispatch:       # allow manual run from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      env:
        ZYTE_API_KEY: ${{ secrets.ZYTE_API_KEY }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      run: |
        python main.py
